Add support for status checks using `vc-status-list@1.0`
digitalbazaar/bedrock-vc-verifier pull request #20
Opened 2022-02-01 15:17 UTC by JSAssassin

2022-02-08 02:28 UTC, msporny approved these changes

2022-02-08 15:23 UTC, dlongley requested changes

2022-02-08 15:23 UTC, dlongley commented on lib/status.js
> +        credentialStatusTypeMatches({credential})) {
```suggestion
      credentialStatusTypeMatches({credential})) {
```

2022-02-08 15:23 UTC, dlongley commented on test/mocha/40-credential-status.js
> +  `${revokedRlCredential.id}/50000`;
The status and the list credential can't have the same ID -- they aren't the same thing.

2022-02-08 15:23 UTC, dlongley commented on test/mocha/40-credential-status.js
> +app.get('/status/1/50000',
This approach seems to defeat the privacy purpose of the list design and may be flagged as such -- or erroneously copied by someone else. We may even want to reject status IDs that do this sort of thing and require them to use hash fragments instead.

2022-02-09 16:21 UTC, dlongley approved these changes
RSLGTM.

2022-02-09 16:38 UTC, merged